org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
forge_version=40.1.93
mappings_channel=parchment
mappings_version=2022.11.06

mod_id=sophisticated_vh_compat
mod_name=Sophisticated VH Compat
mod_version=0.0.2
group_name=dev.hoyin1600p.sophisticated_vh_compat
archives_base_name=SophisticatedVHCompat

mixin_version=0.8.5
mixinextras_version=0.4.1
